// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddNewVehicle: typeof import('./components/AddNewVehicle.vue')['default']
    Button: typeof import('./components/Button.vue')['default']
    Home: typeof import('./pages/Home.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./components/Table.vue')['default']
    Trial: typeof import('./components/trial.vue')['default']
  }
}
